version: '3'

services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=user_service
    ports:
      - "5432:5432"

volumes:
  postgres_data: